BEGIN;

-- Give FOUNDER all the same permissions as SUPER_ADMIN
INSERT INTO role_permission (role_id, permission_id)
SELECT r.id, p.id
FROM role r, permission p
WHERE r.name = 'FOUNDER'
  AND p.code IN (
    'ATTENDANCE_BULK_WRITE',
    'ATTENDANCE_OVERRIDE',
    'ATTENDANCE_READ',
    'ATTENDANCE_WRITE',
    'AUTH_ADMIN_MANAGE',
    'EMPLOYEE_COMPENSATION_WRITE',
    'EMPLOYEE_DOCUMENT_WRITE',
    'EMPLOYEE_READ',
    'EMPLOYEE_WRITE',
    'GOV_AUDIT_READ',
    'GOV_DIVISION_READ',
    'GOV_DIVISION_WRITE',
    'GOV_MONTH_CLOSE_READ',
    'GOV_MONTH_CLOSE_WRITE',
    'GOV_PROJECT_READ',
    'GOV_PROJECT_WRITE',
    'GOV_RBAC_READ',
    'GOV_SYSTEM_CONFIG_READ',
    'GOV_SYSTEM_CONFIG_WRITE',
    'INCOME_APPROVE',
    'INCOME_CATEGORY_READ',
    'INCOME_CATEGORY_WRITE',
    'INCOME_CLIENT_READ',
    'INCOME_CLIENT_WRITE',
    'INCOME_CREATE',
    'INCOME_DOCUMENT_READ',
    'INCOME_DOCUMENT_UPLOAD',
    'INCOME_MARK_PAID',
    'INCOME_MONTH_CLOSE_OVERRIDE',
    'INCOME_READ',
    'INCOME_REJECT',
    'INCOME_SUBMIT',
    'INCOME_UPDATE',
    'LEAVE_APPROVE_L1',
    'LEAVE_APPROVE_L2',
    'LEAVE_ATTACHMENT_READ',
    'LEAVE_ATTACHMENT_UPLOAD',
    'LEAVE_BALANCE_GRANT',
    'LEAVE_BALANCE_READ',
    'LEAVE_MONTH_CLOSE_OVERRIDE',
    'LEAVE_REQUEST_CANCEL',
    'LEAVE_REQUEST_CREATE',
    'LEAVE_REQUEST_READ',
    'LEAVE_TYPE_READ',
    'LEAVE_TYPE_WRITE',
    'MONTH_CLOSE_MANAGE',
    'OPS_ALERT_ACK',
    'OPS_ALERT_READ',
    'OPS_ALERT_RESOLVE',
    'OPS_DASHBOARD_READ',
    'OPS_DATA_QUALITY_ACK',
    'OPS_DATA_QUALITY_READ',
    'OPS_DATA_QUALITY_RESOLVE',
    'OPS_DATA_QUALITY_RUN',
    'OPS_INBOX_ACTION',
    'OPS_INBOX_READ',
    'OPS_OVERRIDE_EXECUTE',
    'OPS_OVERRIDE_REQUEST',
    'OPS_OVERRIDE_REVIEW',
    'SYSTEM_FULL_ACCESS',
    'TIMESHEET_APPROVAL_QUEUE_READ',
    'TIMESHEET_APPROVAL_L1',
    'TIMESHEET_APPROVAL_L2',
    'TIMESHEET_READ',
    'TIMESHEET_SUBMIT',
    'TIMESHEET_WORKLOG_WRITE'
  )
  AND NOT EXISTS (
    SELECT 1 FROM role_permission rp
    WHERE rp.role_id = r.id AND rp.permission_id = p.id
  );

COMMIT;
