BEGIN;

ALTER TABLE payslip
  ADD COLUMN IF NOT EXISTS month DATE NULL,
  ADD COLUMN IF NOT EXISTS gross NUMERIC(12,2) NULL,
  ADD COLUMN IF NOT EXISTS total_adjustments NUMERIC(12,2) NULL,
  ADD COLUMN IF NOT EXISTS total_deductions NUMERIC(12,2) NULL,
  ADD COLUMN IF NOT EXISTS net NUMERIC(12,2) NULL,
  ADD COLUMN IF NOT EXISTS payment_status VARCHAR(30) NULL,
  ADD COLUMN IF NOT EXISTS pdf_path VARCHAR(500) NULL;

CREATE INDEX IF NOT EXISTS idx_payslip_month ON payslip(month);

COMMIT;
